services:
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatbackend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: new_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: 
      context: ./backend 
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: new_password
      DB_NAME: chatbackend
      DB_PORT: 5432
    command: ["npm", "run", "start"]
    networks:
      - app-network
    ports:
      - "4000:4000"
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge